name: Build and Deploy v3

on:
  push:
    branches:
      - main
      
jobs:

  preview-and-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: false

    - name: Build
      run: |
        DT=$(date "+%y.%j.")`echo $(date "+%k%M")`
        TAG=${DT:1}
        echo "tag=${TAG}" >> $GITHUB_ENV
        yarn && yarn build
        export base=/maker/build/vue-page-maker-${TAG}/release/ && export dist=./dist/release && yarn && yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        disable_nojekyll: true
        external_repository: jenvan/vue-page-maker
        publish_branch: build
        publish_dir: ./dist
        cname: www.siteimg.cn
        tag_name: ${{ env.tag }}
        tag_message: 'Deployment ${{ env.tag }}'

    - name: Notify
      uses: wei/curl@master
      with:
        args: http://api.fuchijihua.com/dong?title=New%20Version%20Released&content=vue-page-maker%20[${{ env.tag }}](http://101.36.110.180/?action=online%26tag=${{ env.tag }})
        