name: Build and Deploy
on: [push]
jobs:

  preview-and-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: false

    - name: Build
      run: |
        DT=$(date "+%y.%j.")`echo $(date "+%k%M")`
        TAG=${DT:1}
        echo "tag=${TAG}" >> $GITHUB_ENV
        yarn && yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        disable_nojekyll: true
        external_repository: jenvan/vue-page-maker
        publish_branch: build
        publish_dir: ./dist
        tag_name: ${{ env.tag }}
        tag_message: 'Deployment ${{ env.tag }}'
