name: Build and Deploy
on: [push]
jobs:

  preview-and-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        persist-credentials: false

    - name: Build
      run: |
        DT=$(date "+%y.%j.")`echo $(date "+%k%M")`
        TAG=${DT:1}
        echo "tag=${TAG}" >> $GITHUB_ENV
        yarn && yarn build
        export base=/maker/release/vue-page-maker-${TAG}/ && export dist=./release && yarn && yarn build

    - name: Preview
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        disable_nojekyll: true
        external_repository: jenvan/vue-page-maker
        publish_branch: preview
        publish_dir: ./dist
        cname: www.siteimg.cn
        
    - name: Release
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        disable_nojekyll: true
        external_repository: jenvan/vue-page-maker
        publish_branch: release
        publish_dir: ./release
        tag_name: ${{ env.tag }}
        tag_message: 'Deployment ${{ env.tag }}'

    - name: Notify
      uses: wei/curl@master
      with:
        args: http://api.fuchijihua.com/dong?title=http%3A//api.qrserver.com/v1/create-qr-code/%3Fsize%3D250x250%26ecc%3DH%26margin%3D10%26data%3Dhttp%3A//101.36.110.180/%3Faction%3Donline%2526tag%3D${{ env.tag }}
        